fn main() {
    let out_dir = format!("{}/protos", std::env::var("OUT_DIR").unwrap());

    std::fs::create_dir_all(&out_dir).unwrap();

    protobuf_codegen::Codegen::new()
        .pure()
        .out_dir(out_dir)
        .inputs(["protos/rendezvous.proto", "protos/message.proto"])
        .include("protos")
        .customize(protobuf_codegen::Customize::default().tokio_bytes(true))
        .run()
        .expect("Codegen failed.");

    gen_bgdesk_config();
}

fn gen_bgdesk_config() {
    use std::io::Write;
    use std::path::PathBuf;

    let manifest_dir = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let settings_path = manifest_dir.join("../../config/settings.toml");

    println!("cargo:rerun-if-changed={}", settings_path.display());

    let content = std::fs::read_to_string(&settings_path).unwrap_or_else(|_| {
        panic!(
            "config/settings.toml not found at {}.\n\
             Initialize the config submodule: git submodule update --init config",
            settings_path.display()
        )
    });

    let settings: toml::Table = content.parse().expect("invalid config/settings.toml");
    let rs_pub_key_cliente = required_string(&settings, "rs_pub_key");
    let rs_pub_key_suporte = required_string(&settings, "rs_pub_key_suporte");

    let out_path = PathBuf::from(std::env::var("OUT_DIR").unwrap()).join("bgdesk_config.rs");
    let mut file = std::fs::File::create(&out_path).expect("create bgdesk_config.rs");

    writeln!(
        file,
        "// @generated by build.rs from config/settings.toml — DO NOT EDIT"
    )
    .unwrap();
    writeln!(
        file,
        "pub const RS_PUB_KEY_CLIENTE: &str = \"{}\";",
        escape(&rs_pub_key_cliente)
    )
    .unwrap();
    writeln!(
        file,
        "pub const RS_PUB_KEY_SUPORTE: &str = \"{}\";",
        escape(&rs_pub_key_suporte)
    )
    .unwrap();
    writeln!(
        file,
        "pub const RS_PUB_KEY: &str = RS_PUB_KEY_SUPORTE;"
    )
    .unwrap();
}

fn required_string(table: &toml::Table, key: &str) -> String {
    table
        .get(key)
        .and_then(|v| v.as_str())
        .unwrap_or_else(|| panic!("config/settings.toml: missing or invalid `{}`", key))
        .to_owned()
}

fn escape(value: impl AsRef<str>) -> String {
    value
        .as_ref()
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
}
